### ISSUE TITLE
[Skype for Business] Issue with bot response?

### ISSUE THREAD

**Issue by arunnanjundaswamy** [Microsoft/BotBuilder#3712]
Hi,

I am using BotBuilder V 3.11 (.Net). The Skype For Business channel message is getting added with the below additional text.
```css
p.MsoNormal, li.MsoNormal, div.MsoNormal {
margin-top:0in;
margin-right:0in;
margin-bottom:8.0pt;
margin-left:0in;
line-height:107%;
font-size:11.0pt;
font-family:"Calibri",sans-serif;
}
```

Can someone let me know how to resolve this?
